apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-imoy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-imoy
    app.kubernetes.io/part-of: test-annotations-app-rezy
  name: test-annotations-imoy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-imoy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-imoy
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-ewob-tenant/test-annotations-app-rezy/test-annotations-imoy@sha256:599ab41315a74948314b5b649bda29a575b55d99e9366ddcab1d66b021227e2c
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
